<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>bu</description>
   <name>button_Logout</name>
   <tag></tag>
   <elementGuidId>45444369-b69d-4fe2-a8da-275d32780138</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[text()='Logout']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
