<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter Account IDAlias_accountId</name>
   <tag></tag>
   <elementGuidId>160a3c18-fcb5-41ba-ab1f-6f786a2a152f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='accountId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;accountId&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>996c0c20-ba64-4238-a07e-1b28a27e8f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accountId</value>
      <webElementGuid>c2bbfd40-747a-4b11-8f00-cb32247ce7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>cacf16d4-fd64-4987-9b29-f6f11d289e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>32b87b60-8f28-4084-b4f6-2a5f93e7bc8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss1 form-control</value>
      <webElementGuid>bd6a5724-e362-49cd-b063-7d3f2b4b7c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;authLogin&quot;)/div[@class=&quot;p-0 mt-2 col-12 col-sm-12&quot;]/div[@class=&quot;mt-4&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;jss1 form-control&quot;]</value>
      <webElementGuid>95fe4956-3442-43a6-ad63-3370af47e157</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='accountId']</value>
      <webElementGuid>cbcf34ef-add6-4c4d-8d09-1e45f7b8e432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='authLogin']/div/div/div/input</value>
      <webElementGuid>a06bb147-7bef-40a4-8272-3661c8fd6d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ddc80ad2-61f4-4bb0-aa0c-9a7497ee8c4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
